# Generated by Django 5.2.7 on 2025-11-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('CuestID', models.AutoField(primary_key=True, serialize=False)),
                ('CuestNombre', models.CharField(max_length=100)),
                ('CuestVersion', models.CharField(blank=True, max_length=20, null=True)),
                ('CuestActivo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tblCuestionario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('DashboardID', models.AutoField(primary_key=True, serialize=False)),
                ('DashboardNombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tblDashboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoRespaldo',
            fields=[
                ('DocumentoID', models.AutoField(primary_key=True, serialize=False)),
                ('TipoDocumento', models.CharField(max_length=50)),
                ('NombreArchivo', models.CharField(max_length=255)),
                ('RutaArchivo', models.CharField(max_length=500)),
                ('FechaSubida', models.DateTimeField()),
            ],
            options={
                'db_table': 'tblDocumentoRespaldo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DominioPermitido',
            fields=[
                ('DominioID', models.AutoField(primary_key=True, serialize=False)),
                ('DominioEmail', models.CharField(max_length=100, unique=True)),
                ('TipoInstitucion', models.CharField(blank=True, max_length=50, null=True)),
                ('NombreInstitucion', models.CharField(blank=True, max_length=150, null=True)),
                ('Activo', models.BooleanField(default=True)),
                ('FechaCreacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'tblDominioPermitido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoIntento',
            fields=[
                ('EstadoID', models.AutoField(primary_key=True, serialize=False)),
                ('EstadoDescripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tblEstadoIntento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoVerificacion',
            fields=[
                ('EstadoVerifID', models.AutoField(primary_key=True, serialize=False)),
                ('EstadoDescripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tblEstadoVerificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('EstudID', models.AutoField(primary_key=True, serialize=False)),
                ('EstudDNI', models.CharField(max_length=8, unique=True)),
                ('EstudNombres', models.CharField(max_length=50)),
                ('EstudApellidoPaterno', models.CharField(max_length=50)),
                ('EstudApellidoMaterno', models.CharField(max_length=50)),
                ('EstudFechaNac', models.DateField()),
                ('EstudTelefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'tblEstudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('FiltroID', models.AutoField(primary_key=True, serialize=False)),
                ('Edad', models.CharField(blank=True, max_length=10, null=True)),
                ('Genero', models.CharField(blank=True, max_length=10, null=True)),
                ('Institucion', models.CharField(blank=True, max_length=100, null=True)),
                ('Ubicacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tblFiltro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FiltroRecomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tblFiltroRecomendacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialIntentos',
            fields=[
                ('HistorialID', models.AutoField(primary_key=True, serialize=False)),
                ('FechaConsulta', models.DateTimeField()),
            ],
            options={
                'db_table': 'tblHistorialIntentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('InstiID', models.AutoField(primary_key=True, serialize=False)),
                ('InstiNombre', models.CharField(max_length=150)),
                ('InstiDireccion', models.CharField(max_length=150)),
                ('InstiDistrito', models.CharField(max_length=100)),
                ('InstiProvincia', models.CharField(max_length=100)),
                ('InstiRegion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tblInstitucionEducativa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('IntentID', models.AutoField(primary_key=True, serialize=False)),
                ('Confirmado', models.BooleanField(default=False)),
                ('Creado', models.DateTimeField()),
                ('UltimoAutosave', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblIntento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogVerificacion',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('AccionRealizada', models.CharField(max_length=50)),
                ('AdminUserID', models.IntegerField(blank=True, null=True)),
                ('Comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('FechaAccion', models.DateTimeField()),
            ],
            options={
                'db_table': 'tblLogVerificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NivelRiesgo',
            fields=[
                ('NivelRiesgoID', models.AutoField(primary_key=True, serialize=False)),
                ('NivelRiesgoDescripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tblNivelRiesgo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orientador',
            fields=[
                ('OrienID', models.AutoField(primary_key=True, serialize=False)),
                ('OrienDNI', models.CharField(max_length=8, unique=True)),
                ('OrienNombres', models.CharField(max_length=50)),
                ('OrienApellidoPaterno', models.CharField(max_length=50)),
                ('OrienApellidoMaterno', models.CharField(max_length=50)),
                ('OrienFechaNacimiento', models.DateField(db_column='OrienFechaNacimiento')),
                ('OrienInstitucion', models.CharField(max_length=100)),
                ('OrienCargo', models.CharField(max_length=100)),
                ('OrienAreaEspecializacion', models.CharField(max_length=150)),
                ('OrienEmailInstitucional', models.CharField(max_length=100)),
                ('OrienTelefono', models.CharField(max_length=15)),
                ('OrienPerfilProfesional', models.CharField(blank=True, max_length=255, null=True)),
                ('FechaRegistro', models.DateTimeField()),
                ('FechaVerificacion', models.DateTimeField(blank=True, null=True)),
                ('VerificadoPor', models.IntegerField(blank=True, null=True)),
                ('MotivoRechazo', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'tblOrientador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(db_column='token', editable=False, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('used', models.BooleanField(db_column='used', default=False)),
                ('used_at', models.DateTimeField(blank=True, db_column='used_at', null=True)),
            ],
            options={
                'db_table': 'tblPasswordResetToken',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('RecomendacionID', models.AutoField(primary_key=True, serialize=False)),
                ('Carrera', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('Score', models.FloatField(blank=True, null=True)),
                ('Nivel', models.CharField(blank=True, max_length=50, null=True)),
                ('FechaHora', models.DateTimeField()),
            ],
            options={
                'db_table': 'tblRecomendacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('RespID', models.AutoField(primary_key=True, serialize=False)),
                ('RespValor', models.CharField(blank=True, max_length=255, null=True)),
                ('RespFechaHora', models.DateTimeField()),
            ],
            options={
                'db_table': 'tblRespuesta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('RolID', models.IntegerField(primary_key=True, serialize=False)),
                ('RolNombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'tblRol',
                'managed': False,
            },
        ),
    ]
